/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.dao.DAOCliente;
import br.com.fatec.dao.DAOComanda;
import br.com.fatec.dao.DAOProduto;
import br.com.fatec.model.Cliente;
import br.com.fatec.model.ComandaModel;
import br.com.fatec.model.Produto;
import java.util.Collection;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.x509.AttributeNameEnumeration;

/**
 *
 * @author Simone Velosa
 */
public class Comanda extends javax.swing.JFrame {
    private ComandaModel comanda;
    private DAOComanda daoComanda;
    private DAOProduto daoProduto;
    private DAOCliente daoCliente;
    private Produto produto;
    private Cliente cliente;
    /**
     * Creates new form Comanda
     */
    public Comanda() {
        initComponents();
        preparaFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_kidelicia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_tcomanda = new javax.swing.JLabel();
        lbl_comanda = new javax.swing.JLabel();
        txt_comanda = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lbl_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        txt_mesa = new javax.swing.JTextField();
        lbl_mesa = new javax.swing.JLabel();
        lbl_qtd = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JTextField();
        lbl_preco = new javax.swing.JLabel();
        btn_adicionar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_preco = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        lbl_mesa1 = new javax.swing.JLabel();
        txtPrecoUnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbComanda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lbl_kidelicia.setBackground(new java.awt.Color(255, 0, 0));
        lbl_kidelicia.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        lbl_kidelicia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kidelicia.setText("KiDelícia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(lbl_kidelicia)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_kidelicia)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 80);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 560));
        jPanel2.setPreferredSize(new java.awt.Dimension(2000, 680));

        lbl_tcomanda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_tcomanda.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tcomanda.setText("COMANDA");

        lbl_comanda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_comanda.setText("Comanda:");

        txt_comanda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_comandaFocusLost(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_id.setText("Email Cliente:");

        txtEmailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailClienteFocusLost(evt);
            }
        });

        lbl_produto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_produto.setText("Produto:");

        txt_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtoFocusLost(evt);
            }
        });
        txt_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtoActionPerformed(evt);
            }
        });

        lbl_mesa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_mesa.setText("Mesa:");

        lbl_qtd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_qtd.setText("Qtd:");

        txt_qtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qtdFocusLost(evt);
            }
        });

        lbl_preco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_preco.setText("Preço:");

        btn_adicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_adicionar.setText("ADICIONAR");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_excluir.setText("EXCLUIR");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enviar.setText("ENVIAR");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        lbl_mesa1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_mesa1.setText("Preço Unit.");

        tbComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComandaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbComanda);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tcomanda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_id)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl_comanda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_comanda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_mesa)
                                .addComponent(lbl_qtd))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(lbl_preco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_mesa1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_produto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btn_voltar)
                                    .addGap(32, 32, 32)
                                    .addComponent(btn_enviar))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btn_adicionar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_excluir)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_tcomanda)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_comanda)
                    .addComponent(txt_comanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mesa)
                    .addComponent(txt_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mesa1)
                    .addComponent(txtPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_qtd)
                    .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_preco)
                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_produto)
                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adicionar)
                    .addComponent(btn_excluir))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(btn_enviar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 980, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produtoActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        // TODO add your handling code here:
        if (validarCampos()){
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!!!");
        } else {
            setComanda();
            //if (daoComanda.inserirComandaCliente(comanda)) {
                if (daoComanda.InserirProduto(comanda, produto)) {
                    JOptionPane.showMessageDialog(rootPane, "Produto adicionado com sucesso!!!");
                    limparCamposComanda();
                //}
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha ao adicionar o produto!!!");
            }
        }
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void txt_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtoFocusLost
        // TODO add your handling code here:
        produto = new Produto();
        Produto produtoAux;
        produto.setNomeProduto(txt_produto.getText());
        
        if (!txt_produto.getText().equals("")){
            produtoAux = daoProduto.buscarNome(produto);
            if(produtoAux == null){
               JOptionPane.showMessageDialog(rootPane, "Este produto não existe!!!");
                txt_produto.setText("");
            } else
                produto = produtoAux;
                txtPrecoUnit.setText(Float.toString(produto.getPrecoUnitario()));
        }
   
    }//GEN-LAST:event_txt_produtoFocusLost

    private void txt_qtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qtdFocusLost
        // TODO add your handling code here:
        if (!txt_produto.getText().equals("") || !txt_qtd.getText().equals("")) {
            float qtd = Float.parseFloat(txt_qtd.getText());
            txt_preco.setText(Float.toString(qtd*produto.getPrecoUnitario()));
        }
    }//GEN-LAST:event_txt_qtdFocusLost

    private void txt_comandaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_comandaFocusLost
        // TODO add your handling code here:
        if (!txt_comanda.getText().equals("")) {
            comanda = new ComandaModel();
            comanda.setIdComanda(Integer.parseInt(txt_comanda.getText()));
            comanda.setProdutos(daoComanda.BuscarProdutos(Integer.parseInt(txt_comanda.getText())));
            preencherGridComanda();
        }
    }//GEN-LAST:event_txt_comandaFocusLost

    private void txtEmailClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailClienteFocusLost
        // TODO add your handling code here:
        if (!txtEmailCliente.getText().equals("")) {
            cliente = new Cliente();
            cliente.setEmail(txtEmailCliente.getText());
            cliente = daoCliente.buscar(cliente);
            if (cliente == null) {
                JOptionPane.showMessageDialog(rootPane, "Cliente não possui cadastro!!!");
                txtEmailCliente.setText("");
                txtEmailCliente.requestFocus();
            }
        }
    }//GEN-LAST:event_txtEmailClienteFocusLost

    private void tbComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComandaMouseClicked
        produto = null;
        produto = new Produto();
        int linha = tbComanda.getSelectedRow();
        int idProduto = (Integer) tbComanda.getValueAt(linha, 0);
        //int idComanda = Integer.parseInt(txt_comanda.getText());
        produto.setId(idProduto);
        Produto pAux = daoProduto.buscar(produto);
        
        if(!(pAux == null)) {
            txt_produto.setText(pAux.getNomeProduto());
        }
    }//GEN-LAST:event_tbComandaMouseClicked

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        produto = null;
        comanda = null;
        if (!txt_produto.getText().equals("") || !txt_comanda.getText().equals("")) {
            comanda = new ComandaModel();
            produto = new Produto();
            
            produto.setNomeProduto(txt_produto.getText());
            comanda.setIdComanda(Integer.parseInt(txt_comanda.getText()));
            
            produto = daoProduto.buscarNome(produto);
            if (daoComanda.excluirProdutoComanda(comanda, produto)) {
                JOptionPane.showMessageDialog(rootPane, "Produto removido da comanda com sucesso!!!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha ao remover o produto!!!");
            }
            limparCamposComanda();
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        if(comanda == null)
            comanda = new ComandaModel();
        
        if (!txt_comanda.getText().equals("")) {
            comanda.setStatus("Pendente");
            if(daoComanda.alterar(comanda)) {
                JOptionPane.showMessageDialog(rootPane, "Pedido realizado com sucesso!!!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao enviar o pedido!!!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,"Preencha os campos corretamente!!!");
        }
        limparCamposComanda();
    }//GEN-LAST:event_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_comanda;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_kidelicia;
    private javax.swing.JLabel lbl_mesa;
    private javax.swing.JLabel lbl_mesa1;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JLabel lbl_qtd;
    private javax.swing.JLabel lbl_tcomanda;
    private javax.swing.JTable tbComanda;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtPrecoUnit;
    private javax.swing.JTextField txt_comanda;
    private javax.swing.JTextField txt_mesa;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_produto;
    private javax.swing.JTextField txt_qtd;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void preparaFormulario(){
        daoComanda = new DAOComanda();
        daoProduto = new DAOProduto();
        daoCliente = new DAOCliente();
        limparCamposComanda();
        txt_preco.setEnabled(false);
        txtPrecoUnit.setEnabled(false);
    }
    
    /**
     *
     */
    public void limparCamposComanda(){
        txt_comanda.setText("");
        txtEmailCliente.setText("");
        txt_mesa.setText("");
        txt_preco.setText("");
        txt_produto.setText("");
        txt_qtd.setText("");
        txt_comanda.requestFocus();
    }

    /**
     *
     * @return
     */
    public boolean validarCampos(){
        if (txt_comanda.getText().equals("") || txt_mesa.getText().equals("") || txt_preco.getText().equals("") ||
                txt_produto.getText().equals("") || txt_qtd.getText().equals("") || txtEmailCliente.getText().equals(""))
            return true;
        else
            return false;
    }
    
    /**
     *
     */
    public void setComanda(){
        LinkedList<Produto> produtos = new LinkedList<>();
        produtos.add(produto);
        comanda = new ComandaModel();       
        comanda.setIdComanda(Integer.parseInt(txt_comanda.getText()));
        comanda.setCliente(cliente);
        comanda.setProdutos(produtos);
        comanda.setQtd(Integer.parseInt(txt_qtd.getText()));
    }
    
    /**
     *
     */
    public void preencherGridComanda() {
        //PREENCHER O GRID COM OS ITENS DA COMANDA PESQUISADA
        DefaultTableModel tabela;
        
        try {
            Collection<Produto> produtosComanda = daoComanda.BuscarProdutos(comanda.getIdComanda());
            
            Vector colunas = new Vector();
            colunas.add("ID");
            colunas.add("PRODUTO");
            colunas.add("PREÇO UNIT.");
            //colunas.add("QTD.");
            
            Vector linhas = new Vector();
            
            for (Produto p : produtosComanda) {
                Vector registro = new Vector();
                registro.add(p.getId());
                registro.add(p.getNomeProduto());
                registro.add(p.getPrecoUnitario());
                
                linhas.add(registro);
            }
            
            tabela = new DefaultTableModel(linhas,colunas);
            
            tbComanda.setModel(tabela);
            
        } catch (Exception ex) {
            
        }
    }
}
