/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.dao.DAOEstoque;
import br.com.fatec.dao.DAOProduto;
import br.com.fatec.model.Estoque;
import br.com.fatec.model.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author Simone Velosa
 */
public class Reposicao extends javax.swing.JFrame {

    int confere = 0;
    /**
     * Creates new form Comanda
     */
    public Reposicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_kidelicia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cadarpio = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        lbl_preco = new javax.swing.JLabel();
        btn_atualizar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        txt_id = new javax.swing.JFormattedTextField();
        lbl_qtd = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JTextField();
        lbl_precototal = new javax.swing.JLabel();
        txt_precototal = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lbl_kidelicia.setBackground(new java.awt.Color(255, 0, 0));
        lbl_kidelicia.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        lbl_kidelicia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kidelicia.setText("KiDelícia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(lbl_kidelicia)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_kidelicia)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 80);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 560));
        jPanel2.setPreferredSize(new java.awt.Dimension(2000, 680));

        lbl_cadarpio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_cadarpio.setForeground(new java.awt.Color(255, 0, 0));
        lbl_cadarpio.setText("REPOSIÇÃO DE ESTOQUE");

        lbl_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_id.setText("ID");

        lbl_produto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_produto.setText("Produto");

        lbl_preco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_preco.setText("Preço R$");

        btn_atualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_atualizar.setText("ATUALIZAR");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar.setText("VOLTAR");

        lbl_qtd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_qtd.setText("Qtd.");

        lbl_precototal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_precototal.setText("Preço Total R$");

        btn_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(lbl_cadarpio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(lbl_qtd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(btn_voltar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_buscar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_produto)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_preco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_precototal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_precototal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(btn_atualizar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_cadarpio)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_qtd)
                    .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_preco))
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_produto)
                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precototal)
                    .addComponent(txt_precototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_voltar)
                    .addComponent(btn_buscar))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 980, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
      /*  System.out.println("txt");
        Estoque estoque = null;
        Produto produto = null;
        if(!txt_produto.getText().equals("")){
            System.out.println("Até aqui foi");
            produto.setNomeProduto(txt_produto.getText());
            estoque.setProduto(produto);
            float total;
            DAOEstoque daoestoque = null;
            estoque = daoestoque.BuscaProduto(estoque);
            txt_produto.setText(estoque.getProduto().getNomeProduto());
            txt_id.setText(String.valueOf(estoque.getProduto().getId()));
            txt_preco.setText(String.valueOf(estoque.getProduto().getPrecoUnitario()));
            txt_qtd.setText(String.valueOf(estoque.getQtde()));
            total = estoque.getProduto().getPrecoUnitario() * estoque.getQtde();
            txt_precototal.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(rootPane, "Produto encontrado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo de produto !!!");
        }
        */
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        if(!txt_produto.getText().equals("")){
            Estoque estoque = new Estoque();
            estoque = busca();
            txt_produto.setText(estoque.getProduto().getNomeProduto());
            txt_id.setText(String.valueOf(estoque.getProduto().getId()));
            txt_preco.setText(String.valueOf(estoque.getProduto().getPrecoUnitario()));
            txt_qtd.setText(String.valueOf(estoque.getQtde()));
            Double total;
            total = (Double.parseDouble(txt_preco.getText()) * Double.parseDouble(txt_qtd.getText()));
            txt_precototal.setText(String.valueOf(total));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo de produto !!!");
            limpaCampos();
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
        Estoque estoque;           
            DAOEstoque daoEstoque = new DAOEstoque();
            estoque = busca();
            estoque.setQtde(Integer.parseInt(txt_qtd.getText()));
            if(daoEstoque.alterar(estoque))
                JOptionPane.showMessageDialog(rootPane, "Alteração realizada !");
            else
                JOptionPane.showMessageDialog(rootPane, "Atualização mal sucedida !");
    }//GEN-LAST:event_btn_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reposicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_cadarpio;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_kidelicia;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_precototal;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JLabel lbl_qtd;
    private javax.swing.JFormattedTextField txt_id;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_precototal;
    private javax.swing.JTextField txt_produto;
    private javax.swing.JTextField txt_qtd;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        txt_id.setText("");
        txt_preco.setText("");
        txt_precototal.setText("");
        txt_produto.setText("");
        txt_qtd.setText("");
        txt_id.requestFocus();
    }
    
    public Estoque busca(){
        Estoque estoque = new Estoque();
        Produto produto = new Produto();
        produto.setNomeProduto(txt_produto.getText());
        estoque.setProduto(produto);
        float total;
        DAOEstoque daoestoque = new DAOEstoque();
        estoque = daoestoque.BuscaProduto(estoque);
        return estoque;
    }

}
